Repository girlscriptjaipur/HacktoberFest, pull requests merged in 2019-10, with the labels that each got.

#1 Added Merge Sort
  Merge Sort/merge_sort.cpp
Labels: Hacktoberfest, enhancement

#3 Create fibo.cpp
  fibo.cpp
Labels: Bonus, Hacktoberfest, enhancement, good first issue

#2 Create binary_search.cpp
  Binary Search algo/binary_search.cpp
Labels: Bonus, Hacktoberfest

#6 Bubble Sort added
  Bubble Sort/BubbleSort.C
Labels: Hacktoberfest

#7 Created Dijkstra.cpp
  Dijkstra Algo/Dijkstra.cpp
Labels: Hacktoberfest
